### ISSUE TITLE
Module v4l2loopback not found

### ISSUE THREAD

**Issue by franknitty69** [umlaeute/v4l2loopback#102]
I am able to install v4l2loopback 0.9.1 via smart install v4l2loopback on a yocto linux instance. But executing modprobe v4l2loopback results in the following error:

**modprobe: FATAL: Module v4l2loopback not found.**

i am running the command as root. any suggestions on why modprobe doesn't recognize that v4l2loopback is installed?

**Comment by umlaeute** [comment]
i guess `smart install` isn't smart enough.

unfortunately i am neither, so you might ask the yocto/smart-install people instead.

(closing this ticket, as it is impossible to do anything about it in *our* side)
