### ISSUE TITLE
Xubuntu 16.04 with skype

### ISSUE THREAD

**Issue by xav12358** [umlaeute/v4l2loopback#123]
The stream works properly on vlc but on skype not.
It is written "dummy video device (0x0000) /dev/video0)"

Is it a wrong installation of v4l2loopback?

**Comment by umlaeute** [comment]
thanks for the bug-report.

have you checked #23, #24 and the [wiki](../wiki/Skype)?

also i don't know which version of `v4l2loopback` comes with Xubuntu-16.04, nor which version of `Skype` you happen to have installed.

**Comment by umlaeute** [comment]
closing due to inativity
