### ISSUE TITLE
Failed to open video stream from v4l2loopback device on Nvidia Jetson TK1 and Nvidia Jetson TX1

### ISSUE THREAD

**Issue by crogerjack** [umlaeute/v4l2loopback#125]
![screenshot from 2017-01-18 20-08-00](https://cloud.githubusercontent.com/assets/16471997/22063460/ebcb53b6-ddb9-11e6-8501-f7833a3ebbc0.png)

Hi, the Gstreamer pipeline that I used can work on Intel platform but not on ARM platform.

**Comment by umlaeute** [comment]
please describe the problem and the errors you get.
please paste error messages as text.
use images *only* to illustrate things that cannot be expressed (easily) with plain text.
