### ISSUE TITLE
Cant copy /video/dev0 camera to 3 virtual devices 

### ISSUE THREAD

**Issue by iashwinprasada** [umlaeute/v4l2loopback#135]
**Environment**

v4l2loopback version: latest 0.10

kernel version: Linux LeMaker 3.10.100 #1 SMP PREEMPT Sun Dec 18 06:36:37 PST 2016 armv7l armv7l armv7l GNU/Linux
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04

**This script with videotestsrc as a replacement for camera works fine**

    gst-launch-1.0 videotestsrc ! video/x-raw,width=1280,height=720 ! clockoverlay halignment=right valignment=bottom time-format="%d/%m/%Y %H:%M:%S" ! tee name=t \
            t. ! queue ! v4l2sink sync=false device=/dev/video1 \
            t. ! queue ! v4l2sink sync=false device=/dev/video2 \
            t. ! queue ! v4l2sink sync=false device=/dev/video3 \
            t. ! queue ! v4l2sink sync=false device=/dev/video4

**For Actual camera this is the script, this just doesn't run on the board. keep getting internal data flow error**

~~~
gst-launch-1.0 v4l2src device=/dev/video0 ! tee name=t \
    t. ! queue ! v4l2sink sync=false device=/dev/video1 \
    t. ! queue ! v4l2sink sync=false device=/dev/video2 \
    t. ! queue ! v4l2sink sync=false device=/dev/video3 \
    t. ! queue ! v4l2sink sync=false device=/dev/video4
~~~

**Comment by umlaeute** [comment]
given the problem description, this sounds more like a problem with gstreamer and/or your pipleline than with `v4l2loopback`.

(if you find other evidence that the problem can be solved on `v42loopback`s side, please add it to the ticket and I will reopen it)
