### ISSUE TITLE
Writing arbitrary data and reading as webcam. OpenCV ---write()--> /dev/video0 ---read()--> GoogleChrome/Mozilla/Chromium/Whatever

### ISSUE THREAD

**Issue by TheSalarKhan** [umlaeute/v4l2loopback#138]
### My Environment

  * `v4l2loopback` version: v4l2loopback driver version 0.10.0 loaded

  * kernel version: Linux viper 4.4.0-75-generic #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

  * Distribution (+version):
    Distributor ID:	Ubuntu
    Description:	Ubuntu 16.04.1 LTS
    Release:	16.04
    Codename:	xenial
  
### The Problem:
  I've setup the loopback module with /dev/video0 and /dev/video1, now I want to write some arbitrary data on any one of these from one process, and read that data from the other process. My goal actually is to write RGB frames to the device, using OpenCV, and then I'll be using the loopback device with chromium for integration with WebRTC. to start with I wrote the following program in C and compiled it - no errors or warnings. All I'm doing is simply opening the device:

#### Relevant Code:
```
// main.c
#define _GNU_SOURCE

#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdio.h>

int main( void )
{
    int fileDescriptor = open("/dev/video0",O_DIRECT);

    if(fileDescriptor == -1) {
        perror("ERROR: ");
        return 0;
    }

    printf("All good!");

    return 0;
}
```

#### Observed Results:
Here's the output of the compilation, and this also shows what I'm getting when I run the program:
```
$ gcc main.c -o test
$ ./test
ERROR: : Invalid argument
```
#### Steps to reproduce:

  1. Setup v4l driver, so you have /dev/video0
  2. Just compile the provided code, and run the resulting executable.
  

#### Expected Results:
I think I've been lead astray by my research, I simply want to use the loopback device for writing RGB frames, so that I can read them from any conventional webcam application just like a normal webcam. Please guide me people! Thank you! <3

**Comment by umlaeute** [comment]
you have to write the data as defined by `v4l2 specifications` for *output* devices.

there are some examples in the `examples/` folder
