### ISSUE TITLE
yuv4mpeg_to_v4l2: command not found

### ISSUE THREAD

**Issue by Jassens** [umlaeute/v4l2loopback#145]
Hello,

My environment is:

v4l2loopback version: 0.10
kernel version: 4.10.0.33-generic x86-64
Lubuntu 17.04
       
Executing **videofile=my_file; (yuv4mpeg_to_v4l2 /dev/video0 < /tmp/pipe & ); mplayer $videofile -vf scale=480:360 -vo yuv4mpeg:file=/tmp/pipe** in the examples directory of the v4l2loopback src leads to an error: **yuv4mpeg_to_v4l2: command not found**.

Thank you.

**Comment by umlaeute** [comment]
`yuv4mpeg_to_v4l2` is not in your PATH, run it as `./yuv4mpeg_to_v4l2`
