### ISSUE TITLE
Bananapi - BPI-M2 Berry modprobe error

### ISSUE THREAD

**Issue by bluexmas** [umlaeute/v4l2loopback#147]
### Step 1: Read this

Bananapi - BPI-M2 Berry modprobe error
modprobe: ERROR: could not insert 'v4l2loopback': Exec format **error**

### Step 2: Describe your environment

  * `v4l2loopback` version: _____

          sudo dmesg  | grep -i v4l2loopback

  * kernel version: _____

          Linux bpi-iot-ros-ai 3.10.107-BPI-M2U-Kernel #1 SMP Thu Aug 24 08:01:24 CST 2017 armv7l armv7l armv7l GNU/Linux
    
  * Distribution (+version): _____

LSB Version:    core-9.20160110ubuntu0.2-armhf:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-armhf:security-9.20160110ubuntu0.2-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial  

### Step 3: Describe the problem:

$ sudo modprobe v4l2loopback
modprobe: ERROR: could not insert 'v4l2loopback': Exec format **error**

**Comment by umlaeute** [comment]
I doubt that this is a problem of `v4l2loopback`, it rather looks like a problem with your build setup.

(if you are cross-compiling the module, make sure you use the correct compiler and toolchain to make usable kernel modules)
