### ISSUE TITLE
FFMPEG video0 (webcam) -> video2 (loopback) video3 (loopback)

### ISSUE THREAD

**Issue by jensJJ** [umlaeute/v4l2loopback#151]
### Step 2: Describe your environment

  * `v4l2loopback` version:

`[12420.914648] v4l2loopback: loading out-of-tree module taints kernel.
[12420.916962] v4l2loopback driver version 0.9.1 loaded`

  * kernel version: 

`Linux tinkerboard 4.13.16-rockchip #19 SMP PREEMPT Fri Nov 24 19:34:54 CET 2017 armv7l armv7l armv7l GNU/Linux`

  * Distribution (+version): 
`
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
`

  
### Step 3: Describe the problem:

I am trying to stream the video0 (webcam USB) to 2x virtual loopback video2 and video3 using FFMPEG. I am trying to access video2 or video3 using OpenCV while streaming and it is not receiving any video data.

#### Steps to reproduce:

  1. get video devices

~~~
$ v4l2-ctl --list-devices

   rockchip-rga ():
	/dev/video1

Dummy video device (0x0000) (platform:v4l2loopback-000):
	/dev/video2

Dummy video device (0x0001) (platform:v4l2loopback-001):
	/dev/video3

HD USB Camera (usb-ff540000.usb-1.1):
	/dev/video0
~~~

  2. launch ffmpeg

~~~
ffmpeg -f v4l2 -i /dev/video0 -f v4l2 /dev/video2 -f v4l2 /dev/video3
~~~

  3. Python File OpenCV cam.py

  
#### Observed Results:

~~~
$ ffmpeg -f v4l2 -i /dev/video0 -f v4l2 /dev/video2 -f v4l2 /dev/video3
ffmpeg version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/arm-linux-gnueabihf --incdir=/usr/include/arm-linux-gnueabihf --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, video4linux2,v4l2, from '/dev/video0':
  Duration: N/A, bitrate: 230400 kb/s
    Stream #0:0: Video: rawvideo (YUY2 / 0x32595559), yuyv422, 800x600, 230400 kb/s, 30 fps, 30 tbr, 1000k tbn, 1000k tbc
Output #0, v4l2, to '/dev/video2':
  Metadata:
    encoder         : Lavf56.40.101
    Stream #0:0: Video: rawvideo (YUY2 / 0x32595559), yuyv422, 800x600, q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc
    Metadata:
      encoder         : Lavc56.60.100 rawvideo
Output #1, v4l2, to '/dev/video3':
  Metadata:
    encoder         : Lavf56.40.101
    Stream #1:0: Video: rawvideo (YUY2 / 0x32595559), yuyv422, 800x600, q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc
    Metadata:
      encoder         : Lavc56.60.100 rawvideo
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> rawvideo (native))
  Stream #0:0 -> #1:0 (rawvideo (native) -> rawvideo (native))
Press [q] to stop, [?] for help
frame=    0 fps=0.0 q=0.0 Lq=0.0 size=N/A time=00:00:00.00 bitrate=N/A    
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used)
Exiting normally, received signal 2.
~~~

I get Error: 

~~~
HIGHGUI ERROR: V4L: device /dev/video2: Unable to query number of channels`
~~~

  
#### Expected Results:

  I expected OpenCV to capture from video Index 2
  
#### Relevant Code:

cam.py

~~~python
import numpy as np
import cv2

cap = cv2.VideoCapture(2)

while(True):
    ret, frame = cap.read()
    #gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    #cv2.imshow('frame',gray)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()
~~~

**Comment by umlaeute** [comment]
does it work if you only output to a single virtual device?

**Comment by jensJJ** [comment]
Yes, I also tried with one only. Also following this example:

https://www.timdejong.nl/blog/use-webcam-two-applications-under-linux-simultaneously-using-v4l2loopback

It says that video0 is busy, so something must be run. But I cant get video2.

**Comment by umlaeute** [comment]
if it does work with only one device (which you seem to confirm), then I think the bug is in `ffmpeg` (resp. `OpenVC`).
can you play back the loopback devices with `vlc`

for the timdejog example, this works for me. i'm not sure what you mean with 
> It says that video0 is busy, so something must be run
the example obviously requires that no other application access `/dev/video0` at the same time.

**Comment by jensJJ** [comment]
I mean I have tried to loopback to `/dev/video2` only. And it does not work when I try to ?
`VideoCapture(2)` inside OpenCV. 

I just wanted to check if ffmpeg is doing something on `video0`.

Which example should I try with vlc?

**Comment by jensJJ** [comment]
I tried `vlc v4l2:///dev/video0:width=800:height=600`  . VLC opens, but is not showing a picture. Then I tried `video2` with using dejong v4l2loopback, I get `not a videocapture device`.

**Comment by jensJJ** [comment]
I made it work. I had to set to `-input_format mjpeg and -pix_fmt yuyv422`.

**Comment by umlaeute** [comment]
cool. thanks for the heads up.
