### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by lddd** [umlaeute/v4l2loopback#163]
```
Building v4l2-loopback driver...
make -C /lib/modules/`uname -r`/build M=/root/v4l2loopback modules
make[1]: Entering directory `/usr/src/kernels/3.10.0-693.21.1.el7.x86_64'
arch/x86/Makefile:166: *** CONFIG_RETPOLINE=y, but not supported by the compiler. Toolchain update recommended..  Schluss.
make[1]: Leaving directory `/usr/src/kernels/3.10.0-693.21.1.el7.x86_64'
make: *** [v4l2loopback.ko] Fehler 2
[root@CentOS-74-64-minimal v4l2loopback]# gcc --version
gcc (GCC) 4.9.3
Copyright (C) 2015 Free Software Foundation, Inc.
Dies ist freie Software; die Kopierbedingungen stehen in den Quellen. Es
gibt KEINE Garantie; auch nicht für MARKTGÄNGIGKEIT oder FÜR SPEZIELLE ZWECKE.

[root@CentOS-74-64-minimal v4l2loopback]# 

```

**Comment by umlaeute** [comment]
this is a problem with compiler.
as the error messages says:
> Toolchain update recommended

to build kernel modules, you must use the same (or compatible) compiler that was used to build your kernel. (and you kernel has obviously been built with a kernel that supports mitigation of *Spectre*, which means that it is a rather new compiler (certainly not gcc-4.9.3).

Please consult your distribution documentation (or support channels) to find out how to get the compiler that was used for the kernel.
