### ISSUE TITLE
Failed in directing gstreamer NV12 video to v4l2loopback sink

### ISSUE THREAD

**Issue by WaleedTageldeen** [umlaeute/v4l2loopback#169]
### Enviroment
  * v4l2loopback version: 0.11.0 compiled from source commit 05a03e2b624be632bce4f2260a7211f396bbdff3

  * kernel version: 4.13.0-37-generic

  * Distribution (+version): Ubuntu 16.04.4 LTS
  
### Problem 
The loopback device doesn't accept NV12 pixel format.  I tried to use the v4l2loopback-ctl script to set the loopback device capabilities to NV12 without success.

    ./v4l2loopback-ctl set-caps "video/x-raw, format=NV12" /dev/video1

If I directed the NV12 stream to a fakesink it works correctly.

#### Steps to reproduce:

  Run this pipeline 

    gst-launch-1.0 videotestsrc ! videoconvert ! video/x-raw,format=NV12 ! v4l2sink device=/dev/video1
  
#### Observed Results:

  This is the output of the v4l2loopback-ctl script

    Setting pipeline to PAUSED ...
    libv4l2: error getting pixformat: Invalid argument
    Pipeline is PREROLLING ...
    ERROR: from element /GstPipeline:pipeline0/GstVideoTestSrc:videotestsrc0: Internal data flow error.
    Additional debug info:
    gstbasesrc.c(2948): gst_base_src_loop (): /GstPipeline:pipeline0/GstVideoTestSrc:videotestsrc0:
    streaming task paused, reason not-negotiated (-4)
    ERROR: pipeline doesn't want to preroll.
    Setting pipeline to NULL ...
    Freeing pipeline ...
    output to /dev/video1 failed

And this is the output of running the pipeline mentioned above

    Setting pipeline to PAUSED ...
    libv4l2: error getting pixformat: Invalid argument
    Pipeline is PREROLLING ...
    ERROR: from element /GstPipeline:pipeline0/GstVideoTestSrc:videotestsrc0: Internal data flow error.
    Additional debug info:
    gstbasesrc.c(2948): gst_base_src_loop (): /GstPipeline:pipeline0/GstVideoTestSrc:videotestsrc0:
    streaming task paused, reason not-negotiated (-4)
    ERROR: pipeline doesn't want to preroll.
    Setting pipeline to NULL ...
    Freeing pipeline ...

**Comment by umlaeute** [comment]
currently v4l2loopback does not support NV12.

it's pretty easy to add new formats, just check out [`v4l2loopback_formats.h`](https://github.com/umlaeute/v4l2loopback/blob/master/v4l2loopback_formats.h).

PR are welcome.
