### ISSUE TITLE
Entry in lsusb is not shown

### ISSUE THREAD

**Issue by Kish27051995** [umlaeute/v4l2loopback#170]
This v4l2loopback works fine but i cannot see any entry in lsusb output when this module is inserted. As lsusb output shows all the USB devices present. I have emulated virtual USB through USBIP. 
This USBIP creates an entry in /dev/bus/usb/00* directory and displays the Virtual USB in lsusb output. As its a virtual device, is there any way to link both the fake device node and the USBIP?

**Comment by umlaeute** [comment]
`v4l2loopback` emulates a video-device on the `v4l2` layer, not on the `usb` layer (or any other layers below), so it is no wonder that the device doesn't show up with `lsusb` (or `lspci`)

thus, the quick answer is: no
