### ISSUE TITLE
error to install

### ISSUE THREAD

**Issue by toshibochan** [umlaeute/v4l2loopback#175]
I have errors to install on raspberry pi. 4.14.34-v7+
please I need help.

make
Building v4l2-loopback driver...
make -C /lib/modules/`uname -r`/build M=/home/pi/v4l2loopback modules
make[1]: Entering directory '/lib/modules/4.14.34-v7+/build'
make[1]: *** No rule to make target 'modules'.  Stop.
make[1]: Leaving directory '/lib/modules/4.14.34-v7+/build'
Makefile:42: recipe for target 'v4l2loopback.ko' failed
make: *** [v4l2loopback.ko] Error 2

**Comment by umlaeute** [comment]
this is most likely because your kernel-headers are either not properly configured r because your kernel has been compiled without modules support.
