### ISSUE TITLE
having error trying install

### ISSUE THREAD

**Issue by toshibochan** [umlaeute/v4l2loopback#176]
pi@toshiboPI3:~/v4l2loopback $ make && sudo make install
Building v4l2-loopback driver...
make -C /lib/modules/`uname -r`/build M=/home/pi/v4l2loopback modules
make[1]: *** /lib/modules/4.9.35-v7+/build: No such file or directory.  Stop.
Makefile:42: recipe for target 'v4l2loopback.ko' failed
make: *** [v4l2loopback.ko] Error 2

please help

**Comment by toshibochan** [comment]
this device is raspberry pi jessie

**Comment by umlaeute** [comment]
please follow the "install" instructions in the README.

**Comment by umlaeute** [comment]
i just noticed that you've created multiple (duplicate and/or bogus) issues in the last few hours. please don't.
if you feel that i have closed an issue without justification, please add more information to the (closed) issue (as it can be opened again).
