### ISSUE TITLE
Redistribute latency error while audio streaming

### ISSUE THREAD

**Issue by Harishrelysys** [umlaeute/v4l2loopback#181]
Hi all,
       I am trying to stream vorbis encoded audio using gstreamer.I am getting Redistribute latency error.
       Please tell me is their anymistake in the command 
       
Thank you all inadvance   

**Sender:**

**command:**

```
gst-launch-1.0 -e --gst-debug-level=2 alsasrc device=hw:0,0 latency-time=30000 num-buffers=1000 buffer-time=800000 ! \
audio/x-raw,format=S16LE,layout=interleaved,rate=44100,channels=2 ! audioconvert ! audio/x-raw,format=F32LE,rate=44100,channels=2,layout=interleaved ! \
vorbisenc ! audio/x-vorbis,rate=44100,channels=2 ! vorbisparse ! rtpvorbispay name=pay pt=96 config-interval=3 ! application/x-rtp,media=audio,channel=2,payload=96,clock-rate=44100,encoding-name=VORBIS ! \
udpsink host=192.168.5.30 port=5000
```

**error log:**

> Setting pipeline to PAUSED ...
> Pipeline is live and does not need PREROLL ...
> Setting pipeline to PLAYING ...
> New clock: GstAudioSrcClock
> Redistribute latency...
> ^Chandling interrupt.
> Interrupt: Stopping pipeline ...

**Reciever:**

**command:**

```
gst-launch-1.0 -e --gst-debug-level=2 udpsrc port=5000 ! application/x-rtp,media=audio,channel=2,payload=96,clock-rate=44100,encoding-name=VORBIS ! \
rtpvorbisdepay name=pay0 ! vorbisparse ! vorbisdec ! audio/x-raw,format=F32LE,rate=44100,channel=2 ! audioconvert ! \
autoaudiosink sync=false
```

**error log:**

> Setting pipeline to PAUSED ...
> Pipeline is live and does not need PREROLL ...
> Setting pipeline to PLAYING ...
> New clock: GstSystemClock
> 0:00:00.997245066  3269      0x15c0400 WARN          rtpvorbisdepay gstrtpvorbisdepay.c:376:gst_rtp_vorbis_depay_setcaps:<pay0> no configuration specified
> 0:00:00.997436314  3269      0x15c0400 WARN          rtpvorbisdepay gstrtpvorbisdepay.c:635:gst_rtp_vorbis_depay_process:<pay0> warning: Could not switch codebooks
> WARNING: from element /GstPipeline:pipeline0/GstRtpVorbisDepay:pay0: Could not decode stream.
> Additional debug info:
> gstrtpvorbisdepay.c(635): gst_rtp_vorbis_depay_process (): /GstPipeline:pipeline0/GstRtpVorbisDepay:pay0:
> Could not switch codebooks
> 0:00:01.048326551  3269      0x15c0400 WARN          rtpvorbisdepay gstrtpvorbisdepay.c:635:gst_rtp_vorbis_depay_process:<pay0> warning: Could not switch codebooks
> WARNING: from element /GstPipeline:pipeline0/GstRtpVorbisDepay:pay0: Could not decode stream.
> Additional debug info:
> gstrtpvorbisdepay.c(635): gst_rtp_vorbis_depay_process (): /GstPipeline:pipeline0/GstRtpVorbisDepay:pay0:
> Could not switch codebooks
> 0:00:01.073574969  3269      0x15c0400 WARN          rtpvorbisdepay gstrtpvorbisdepay.c:635:gst_rtp_vorbis_depay_process:<pay0> warning: Could not switch codebooks
> WARNING: from element /GstPipeline:pipeline0/GstRtpVorbisDepay:pay0: Could not decode stream.
> Additional debug info:

**Comment by umlaeute** [comment]
welcome.
this is the bug-tracker of `v4l2loopback`, a kernel driver for virtual video devices.
your question seems to be totally unrelated to this software. please ask at the proper channels.
