### ISSUE TITLE
Question: Is it possible to emulate a USB webcam?

### ISSUE THREAD

**Issue by homotopycolimit** [umlaeute/v4l2loopback#184]
Is there a way I can use v4l2loopback to emulate connecting a USB webcam?

I use v4l2loopback to create a video device /dev/video0. What I would like is to then have this device appear as if it were a USB connected webcam. Is that possible?

**Comment by homotopycolimit** [comment]
something with usb gadget drivers perhaps?

**Comment by umlaeute** [comment]
no. it's out of scope of this project to emulate real hardware.

if you want hardware emulation, use a virtual machine like VirtualBox, which might be able to emulate a (generic) USB camera from any v4l2 device (including `v4l2loopback`). i'm pretty sure that VirtualBox can do this, i don't know about others.
