### ISSUE TITLE
gstreamer copy from webcam to dummy device

### ISSUE THREAD

**Issue by Maobuff** [umlaeute/v4l2loopback#213]
v4l2loopback driver version 0.12.1
kernel 4.14.98-v7+
raspbian stretch

cloning webcam using gstreamer 
gst-launch-1.0 v4l2src ! v4l2sink device=/dev/video1
provide error : libv4l2 : error getting pixformat: Invalid argumen

but when inserting videorate with caps in pipeline (videorate ! image/jpeg,framerate=30/1) im getting same error, but its actually working (with some image random artifacts)

**Comment by umlaeute** [comment]
works for me (on my laptop with `linux-4.19.0-3-amd64`).

**Comment by Maobuff** [comment]
well:) what is yours gstreamer version?

**Comment by umlaeute** [comment]
what is yours?

~~~
$ gst-launch-1.0 --gst-version
GStreamer Core Library version 1.14.4
~~~

**Comment by Maobuff** [comment]
1.10.4
I think gst is incapable of putting coded stream to v4l2sink (only raw pixel format)
Its looks like not implement feature in gst or its just impossible.

**Comment by umlaeute** [comment]
this could well be. my camera doesn't produce any compressed video stream, so i cannot test this.
so you probably have to put a decoder into your pipeline.

closing this, as the problem seems to be related to gstreamer.
