### ISSUE TITLE
v4l2_get_timestamp after trying sudo insmod 

### ISSUE THREAD

**Issue by MuradTroll** [umlaeute/v4l2loopback#214]
### Step 2: Describe your environment

  * `v4l2loopback` version: latest (1.2.1)

  * kernel version: Linux archlabs 5.0.5-arch1-1-ARCH #1 SMP PREEMPT Wed Mar 27 17:53:10 UTC 2019 x86_64 GNU/Linux

  * Distribution (+version):

LSB Version:	1.4
Distributor ID:	ArchLabs
Description:	ArchLabs Linux
Release:	2019.1.20
Codename:	ArchLabs
  
#### Steps to reproduce:

Install as described on the main page, some errormessages but overall everything seems fine

make -C /lib/modules/`uname -r`/build M=/home/murad/Downloads/v4l2loop/v4l2loopback-master modules_install
make[1]: Verzeichnis „/usr/lib/modules/5.0.5-arch1-1-ARCH/build“ wird betreten
  INSTALL /home/murad/Downloads/v4l2loop/v4l2loopback-master/v4l2loopback.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: crypto/bio/bss_file.c:72
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: crypto/bio/bss_file.c:79
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  5.0.5-arch1-1-ARCH
make[1]: Verzeichnis „/usr/lib/modules/5.0.5-arch1-1-ARCH/build“ wird verlassen
  
Afterwards I ran 

sudo insmod v4l2loopback.ko.xz exclusive_caps=1               

and got the following errormessage
                         
insmod: ERROR: could not insert module v4l2loopback.ko.xz: Unknown symbol in module

looking into dmesg I always get the following errormessage after running that insmod command:

v4l2loopback: Unknown symbol v4l2_get_timestamp (err -2)

I tried multiple things before running this command: unloading the module, loading videodev (which kind of was loaded a priori because of intel, at least I couln't unload it with rmmod because it was in use), etc. Nothing seemed to work.

**Comment by umlaeute** [comment]
hmpf. we recently (with #205 )switched to `v4l2_get_timestamp` which [was apparently dropped right before we started using it](https://www.mail-archive.com/linux-media@vger.kernel.org/msg143446.html).

ping @parr0tr1ver
