### ISSUE TITLE
Color in video output is greenish

### ISSUE THREAD

**Issue by haxpor** [umlaeute/v4l2loopback#218]
### Describe your environment

  * `v4l2loopback` version: [  138.058569] v4l2loopback driver version 0.12.1 loaded

          sudo dmesg  | grep -i v4l2loopback

  * kernel version: [  138.058569] v4l2loopback driver version 0.12.1 loaded

          uname -a

  * Distribution (+version): 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

          lsb_release -a
  
### Step 3: Describe the problem:

I successfully built v4l2loopback and installed to my system. OBS can detect my camera, and I'm able to select video device in the UI.

Just that the color output in the video is wrong, I see greenish as in image below.

![Screenshot from 2019-04-23 22-55-36](https://user-images.githubusercontent.com/673757/56594567-adf45100-661f-11e9-841d-4a8ce7c72b23.png)

I've checked with `guvcview` and saw the similar result.

#### Steps to reproduce:

  1. Plug in DSLR camera (nikon d3300) via usb to ubuntu box
  2. follows instruction from README.md both in INSTALL, and RUN section
  3. install `gphoto2` with `sudo install gphoto2` and make sure you have `ffmpeg` installed as well
  3. execute `gphoto2 --stdout --capture-movie | ffmpeg -i - -vcodec rawvideo -pix_fmt yuv420p -threads 0 -f v4l2 /dev/video2`
  4. now check with either OBS or more convenient `guvcview`, you will see similar to above image.
  
#### Observed Results:

  * What happened?  This could be a description, log output, etc.

Color in video output is in greenish and not colors it should be. Checked with OBS, and `guvcview`.
  
#### Expected Results:

  * What did you expect to happen?

Color is consistent.
  
#### Relevant Code:

N/A

**Comment by umlaeute** [comment]
`v4l2loopback` doesn't do any color-conversion. it takes the colourspace and the data as-is from the producer, and passes them to the consumer. (so i'm closing this)

so either:
- the producer sets the wrong colourspace feeding the data to the loopback device
- OR the consumer cannot handle the colourspace it gets and (wrongly) assumes something else


you are passing the raw frames from `gphoto2´ to `ffmpeg` via a pipe. most likely these frames do not have any colourspace information, so you must pass the correct value to ffmpeg.
