### ISSUE TITLE
Ability to flip horizontally and/or vertically

### ISSUE THREAD

**Issue by gbraad** [umlaeute/v4l2loopback#220]
Unable to use the following to flip the video image:

```
v4l2-ctl -c horizontal_flip=0 -d /dev/video1
v4l2-ctl -c horizontal_flip=1 -d /dev/video1
```

as it seems Google's Chrome does not orient the image correctly, while Firefox does. However, these controls aren't available.

**Comment by umlaeute** [comment]
v4l2loopback doesn't do any processing of the image data (no decompression, format conversion, resizing, flipping,...), and it's not planned to add this feature (as this is really user-space code and `v4l2loopback` only runs in kernel-space).

if there's a bug in chromium, it should be fixed there.
if your producer creates images in the wrong orientation, you should fix the producer.
