### ISSUE TITLE
Only one camera is created

### ISSUE THREAD

**Issue by xav12358** [umlaeute/v4l2loopback#221]
Hello,

I have installed v4l2loopback with on ubuntu sources. I have a ubuntu 16.04 desktop.

`  sudo modprobe v4l2loopback`

Then I try to create virtual cameras:

`sudo  modprobe v4l2loopback video_nr=2,3,4`

But only one camera is create which is /dev/video1 ( I already have my webcam on /dev/video0)

Here are more informations on install:

  * `v4l2loopback` version: _____
[  232.789839] v4l2loopback driver version 0.9.1 loaded
  * kernel version: _____
Ubuntu 16.04
Linux xavier-OMEN-by-HP-Laptop 4.15.0-47-generic #50~16.04.1-Ubuntu SMP Fri Mar 15 16:06:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

  * Distribution (+version): _____
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

          
I don't know why only one virtual camera is created.

**Comment by umlaeute** [comment]
the kernel won't load a module that is already loaded.
so you need to unload the module, before you can re-load it with different module parameters:

~~~
# rmmod v4l2loopback
~~~
