### ISSUE TITLE
ioctl(fd, VIDIOC_S_FMT, &format) not working after OS reinstall

### ISSUE THREAD

**Issue by hugomatic** [umlaeute/v4l2loopback#231]
I recently changed the hard disk on my machine and did a fresh reinstall of Ubuntu 18.04.  However I can't get v4l2loopback to work anymore, even though it was running fine on the same hardware before.

 
Here's my setup:
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

 
uname -a
Linux sixy 5.0.0-25-generic #26~18.04.1-Ubuntu SMP Thu Aug 1 13:51:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

sudo dmesg  | grep -i v4l2loopback
[ 2616.308572] v4l2loopback driver version 0.10.0 loaded
[532669.139958] v4l2loopback driver version 0.10.0 loaded
[538525.465299] v4l2loopback driver version 0.10.0 loaded
[538560.316585] v4l2loopback driver version 0.10.0 loaded
[601450.990878] v4l2loopback driver version 0.10.0 loaded
[602970.826693] v4l2loopback driver version 0.10.0 loaded
[603710.979479] v4l2loopback driver version 0.10.0 loaded
```

It looks like its configured correctly
```
:~/code/v4l2loopback/examples$ v4l2-ctl --list-devices
Dummy video device (0x0000) (platform:v4l2loopback-000):
	/dev/video0
```

But even the test program fails to set the format:
```
~/code/v4l2loopback/examples$ ./test /dev/video0 
using output device: /dev/video0
test: test.c:140: main: Assertion `ret_code != -1' failed.
Aborted
```

I would happily reinstall everything again but I'm not sure if its going to help, and I would like to understand what's going on.

**Comment by umlaeute** [comment]
you might want to start with the latest release of *v4l2loopback*, which is **0.12.2** (rather than the *0.10.0* you are using).

i'll close this issue for now. if the problem persists with 0.12.2, just add additional information and i can re-open it.
