### ISSUE TITLE
Kernel Header mismatch?

### ISSUE THREAD

**Issue by mgoeller** [umlaeute/v4l2loopback#234]
Hello

I worked the last 6 months with v4l2loopback on a Raspberry Pi Model 3 B+. Now I got a new model 4, and tried from scratch. I'm running the latest Raspbian Buster Lite with sudo apt-get update und upgrade done.

My linux kernel is:
`uname -a
Linux raspberrypi 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux
`

and the output of _apt-cache policy raspberrypi-kernel raspberrypi-kernel-headers_
`raspberrypi-kernel:
  Installed: 1.20190925-1
  Candidate: 1.20190925-1
  Version table:
 *** 1.20190925-1 100
        100 /var/lib/dpkg/status
     1.20190819-1 500
        500 http://archive.raspberrypi.org/debian buster/main armhf Packages
raspberrypi-kernel-headers:
  Installed: 1.20190819-1
  Candidate: 1.20190819-1
  Version table:
 *** 1.20190819-1 500
        500 http://archive.raspberrypi.org/debian buster/main armhf Packages
        100 /var/lib/dpkg/status`

trying to sudo make in the v4l2 directory returns me the following error:
`pi@raspberrypi:~/v4l2loopback $ make
Building v4l2-loopback driver...
make -C /lib/modules/`uname -r`/build M=/home/pi/v4l2loopback modules
make[1]: *** /lib/modules/4.19.75-v7l+/build: No such file or directory.  Stop.
make: *** [Makefile:43: v4l2loopback.ko] Error 2`

If I ls into the /lib/modules/ directory I have a folder with the kernel version but no _built_ directory.
`pi@raspberrypi:/lib/modules/4.19.75-v7l+ $ ls
kernel             modules.builtin      modules.dep.bin  modules.softdep
modules.alias      modules.builtin.bin  modules.devname  modules.symbols
modules.alias.bin  modules.dep          modules.order    modules.symbols.bin`

**Comment by umlaeute** [comment]
please ask on some raspbian forum how to install all relevant kernel headers.

you might also want to install the `v4l2loopback-dkms` package first (even if it gives you an outdated version) to pull in the build infrastructure.
