### ISSUE TITLE
does not work since the last update of kernel

### ISSUE THREAD

**Issue by corinnespi** [umlaeute/v4l2loopback#236]
### Step 1: Read this

Thanks for your feedback. It is invaluable for making `v4l2loopback` a better
software.

To help us making the most of your feedback (so we can e.g. fix bugs more
quickly), please make sure to provide the following information.

#### Accessibility
Sometimes pictures say more.
However, mostly they prevent the use of advanced
tools (like "search" or "copy&paste").
And always they prevent people who don't use graphical browser to access the
tracker from reading your content.
So, to make the web a better place, we ask you to post *text* rather than
*screenshots of text* whenever feasible (pretty much always).

#### Cruft

Please exclude these instructions (and other non-relevant information) from your
report.

### Step 2: Describe your environment

  * `v4l2loopback` version: v4l2loopback-0.12.1 (i suppose)

          sudo dmesg  | grep -i v4l2loopback

  * kernel version: Linux corinnes-N2x0WU 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

          uname -a

  * Distribution (+version): Ubuntu 18.04

          lsb_release -a
  
### Step 3: Describe the problem:
 v4l2loopback does not create a new virtual cam when I do
sudo modprobe v4l2loopback
There is only my normal webcam that is listed when I do v4l2-ctl --list-devices
Previously it was working. 

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, log output, etc.
  
#### Expected Results:

  * What did you expect to happen?
Create a virtual cam to be able tu use is with obs studio and zoom ! 
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by umlaeute** [comment]
i've closed this because i only saw the template (and no actual information).
please edit the text and remove all "cruft" from the template (as the template asks you to do), so only the relevant information is shown.
i'll then re-open the issue.
