### ISSUE TITLE
No such file or directory.

### ISSUE THREAD

**Issue by Leoruiz197** [umlaeute/v4l2loopback#240]
hello anyone can help me?

pi@raspberrypi:~/v4l2loopback $ make
Building v4l2-loopback driver...
make -C /lib/modules/`uname -r`/build M=/home/pi/v4l2loopback modules
make[1]: *** /lib/modules/4.19.75-v7+/build: No such file or directory.  Stop.
make: *** [Makefile:43: v4l2loopback.ko] Error 2

**Comment by umlaeute** [comment]
you did read the [README](https://github.com/umlaeute/v4l2loopback#DEPENDENCIES) before you posted your problem, did you?
