### ISSUE TITLE
Raspberry Pi compiling issue

### ISSUE THREAD

**Issue by danriches** [umlaeute/v4l2loopback#245]
Please see second post below..

**Comment by danriches** [comment]
I can;t seem to compile this on an RPi 4B (2Gb) running latest version of Raspbian Buster:

pi@rpi4b2g:~/v4l2loopback $ make
Building v4l2-loopback driver...
make -C /lib/modules/`uname -r`/build M=/home/pi/v4l2loopback modules
make[1]: *** /lib/modules/4.19.81-v7l+/build: No such file or directory.  Stop.
make: *** [Makefile:43: v4l2loopback.ko] Error 2

Any Idea's anyone????

Thanks in advance, Dan

**Comment by danriches** [comment]
I ended up running the commands under package install and it worked. I did everything there was to do on the manual source build and install but no, at least it's loaded the kernel module with 2 output devices as I wanted.

Thank you and sorry for the stupid questions, I should've tried harder first off ;)

Dan

**Comment by mysunnytime** [comment]
> I ended up running the commands under package install and it worked. I did everything there was to do on the manual source build and install but no, at least it's loaded the kernel module with 2 output devices as I wanted.
> 
> Thank you and sorry for the stupid questions, I should've tried harder first off ;)
> 
> Dan

Hi! I encountered the same error. May I ask how did you install it with "command under package install"? I don't find it in readme.. Thanks!
