### ISSUE TITLE
v4l2loopback in docker - getting error ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/5.0.0-38-generic/modules.builtin.bin'

### ISSUE THREAD

**Issue by baijupadmanabhan** [umlaeute/v4l2loopback#253]
Step 24/27 : RUN cd v4l2loopback-master; make && make install && depmod -a
 ---> Running in 4efda0b563be
Building v4l2-loopback driver...
make -C /lib/modules/`uname -r`/build M=/app/v4l2loopback-master modules
make[1]: Entering directory '/usr/src/linux-headers-5.0.0-38-generic'
  CC [M]  /app/v4l2loopback-master/v4l2loopback.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /app/v4l2loopback-master/v4l2loopback.mod.o
  LD [M]  /app/v4l2loopback-master/v4l2loopback.ko
make[1]: Leaving directory '/usr/src/linux-headers-5.0.0-38-generic'
make -C /lib/modules/`uname -r`/build M=/app/v4l2loopback-master modules_install
make[1]: Entering directory '/usr/src/linux-headers-5.0.0-38-generic'
  INSTALL /app/v4l2loopback-master/v4l2loopback.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: ../crypto/bio/bss_file.c:72
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: ../crypto/bio/bss_file.c:79
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  5.0.0-38-generic
Warning: modules_install: missing 'System.map' file. Skipping depmod.
make[1]: Leaving directory '/usr/src/linux-headers-5.0.0-38-generic'
depmod: WARNING: could not open /lib/modules/5.0.0-38-generic/modules.order: No such file or directory
depmod: WARNING: could not open /lib/modules/5.0.0-38-generic/modules.builtin: No such file or directory
Removing intermediate container 4efda0b563be
 ---> e22bd47adc5c
Step 25/27 : COPY ./test.mp4 /app/
 ---> 49f3c9d17dd6
Step 26/27 : RUN modprobe v4l2loopback
 ---> Running in 4cfe159c0d09
modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/5.0.0-38-generic/modules.builtin.bin'
modprobe: ERROR: could not insert 'v4l2loopback': Operation not permitted
The command '/bin/sh -c modprobe v4l2loopback' returned a non-zero code: 1

Describe your environment

  * `v4l2loopback` version: 

Took latest git master branch zip file to build.

  * kernel version: _____

5.0.0-38-generic

  * Distribution (+version): _____

 DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"

 #### Relevant Code:
Dockerfile
  ```
 FROM ubuntu
USER root
RUN apt-get update
RUN echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list
RUN apt-get install -y gnupg2
COPY ./linux_signing_key.pub /tmp/linux_signing_key.pub
RUN apt-key add /tmp/linux_signing_key.pub
RUN apt-get update


RUN apt-get install unzip -y
RUN apt-get install v4l-utils -y
#RUN apt-get install v4l2loopback-dkms -y
RUN apt-get install ffmpeg -y
RUN apt-get install dkms -y


RUN echo "deb http://security.ubuntu.com/ubuntu disco-security main" >> /etc/apt/sources.list
RUN apt-get update
RUN apt-get install linux-headers-5.0.0-38 -y

WORKDIR /app

COPY ./linux-headers-5.0.0-38-generic_5.0.0-38.41_amd64.deb /app/
RUN apt install ./linux-headers-5.0.0-38-generic_5.0.0-38.41_amd64.deb -y

COPY ./v4l2loopback-master.zip /app/
RUN unzip v4l2loopback-master.zip

RUN cd v4l2loopback-master; make && make install && depmod -a

#COPY ./v4l2loopback-dkms_0.9.1-4ubuntu0.1_all.deb /app/
#RUN apt install ./v4l2loopback-dkms_0.9.1-4ubuntu0.1_all.deb -y

COPY ./test.mp4 /app/

RUN modprobe v4l2loopback

CMD [ "/bin/bash", "-c","ffmpeg -re -stream_loop -1 -i test.mp4 -map 0:v -f v4l2 /dev/video0" ]
  ```

**Comment by umlaeute** [comment]
loading a kernel-module inside a docker-container?

this won't work due to the design of docker-containers. see https://stackoverflow.com/a/33017933/1169096
