### ISSUE TITLE
modprobing fails to create /dev/video

### ISSUE THREAD

**Issue by daoudr** [umlaeute/v4l2loopback#254]
I cannot create /dev/video https://i.imgur.com/2NKYGbV.png after modprobing

**Comment by umlaeute** [comment]
please post any logs/output in text-format.

quoting the bugreport template:

> 
> #### Accessibility
> Sometimes pictures say more.
> However, mostly they prevent the use of advanced tools (like "search" or "copy&paste").
> And always they prevent people who don't use graphical browser to access the tracker from reading your content.
> So, to make the web a better place, we ask you to post *text* rather than *screenshots of text* whenever feasible (pretty much always).
