### ISSUE TITLE
V4L2 errors....

### ISSUE THREAD

**Issue by RioChan** [umlaeute/v4l2loopback#262]
Hi Sir:
I know there are bunches of error of V4L2 that people met.
Those 2 issues are happening on my site, even I try this solution already several times.

Solutions is here:
https://stackoverflow.com/questions/28712079/gstreamer-error-pipeline-could-not-be-constructed-no-element-v4l2src

Issue #1, I met here is I have no plugin the v4lsrc.
gst-inspect-1.0 v4l2src
No such element or plugin 'v4l2src'

Issue #2, I connect my Iphone with ubuntu 18.04, and I have the second line error:
: Device has no format negotiated.

root@ubuntu:/opt/openface/v4l2loopback# v4l2-ctl -d /dev/video0 -c timeout=3000
root@ubuntu:/opt/openface/v4l2loopback# v4l2loopback-ctl set-timeout-image service-unavailable.png /dev/video0
Device has no format negotiated

May champion guide me how to resolve this?
I stuck here for weeks... Sadly, I Found no solution...

BR Rio

**Comment by umlaeute** [comment]
your issue No.1 is *really unrelated* to `v4l2loopback`, that's a problem with your GStreamer setup.

i don't really understand your issue No.2. i have no clue what your Iphone has to do with `v4l2loopback`.
However, if you want to set a `timeout_image` you must first fixate the format of the videostream (the timeout-image will be converted to this format).
The simplest way is probably to use the `set-caps` command of `v4l2loopback-ctl`:

~~~sh
v4l2-ctl -d /dev/video0 -c timeout=3000
v4l2loopback-ctl set-caps "video/x-raw,format=UYVY,width=640,height=480" /dev/video0
v4l2loopback-ctl set-timeout-image service-unavailable.png /dev/video0
~~~
