### ISSUE TITLE
VFL_TYPE_GRABBER not declared

### ISSUE THREAD

**Issue by weidtn** [umlaeute/v4l2loopback#284]
Linux 5.7.0.1-MANJARO

I did a fresh `git clone`, when running `make` I get an error for function `init_vdev` because `VFL_TYPE_GRABBER` is not declared.

**Comment by freundTech** [comment]
I ran a `git bisect` on the kernel and found this commit: https://github.com/torvalds/linux/commit/3e30a927af3ca86f6556faf437da44ca8bcf54a4

I'll try if renaming is enough.

**Comment by freundTech** [comment]
I fixed it and created a pull request here: #285

**Comment by weidtn** [comment]
Sorry, I did not search in PR. I only searched in the issues.
