### ISSUE TITLE
Unable to create camera and connect to them

### ISSUE THREAD

**Issue by Suryansh5545** [umlaeute/v4l2loopback#287]
I am trying to use avatarify but it is unable to connect to dev/video0
![Screenshot_20200418_180752](https://user-images.githubusercontent.com/34577232/79637820-cac65480-819f-11ea-9004-cd31965241a8.png)

i also tried to create another camera but nothing happen when i enter the command 
Please Help me

**Comment by umlaeute** [comment]
if you want this ticket to be re-opened, please post console-output as text rather than screenshots, as per [the docs](https://github.com/umlaeute/v4l2loopback/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#accessibility).
