### ISSUE TITLE
modprobe: ERROR: could not insert 'v4l2loopback': Exec format error

### ISSUE THREAD

**Issue by unicornofdeath** [umlaeute/v4l2loopback#288]
I get this error 
I have tried to build from source I have download with apt-get I have tried everything and still get error
From 
```
sudo dmesg | grep -i v4l2loopback
```
I get when installed with apt-get
```
[  708.957747] v4l2loopback: loading out-of-tree module taints kernel.
[  708.957936] v4l2loopback: module verification failed: signature and/or required key missing - tainting kernel
```

**Comment by wick-ed** [comment]
Hi @unicornofdeath 

was the same for me (Ubuntu 18.04).
[This issue's comment](https://github.com/umlaeute/v4l2loopback/issues/260#issuecomment-598653025) gave me the solving hint.
Just did `make CC=/usr/bin/gcc` instead of a blank `make`.
After that the modprobe command worked. Using the loopback to stream from OBS. :)

**Comment by unicornofdeath** [comment]
I have tried that and still get same error

**Comment by umlaeute** [comment]
> I get this error

which one (probably the one from the title; but it makes a bug-report *much* easier to read if you don't have to jump through the page for each line)

>  I have tried to build from source I have download with apt-get I have tried everything and still get error

sorry, i don't understand this sentence.

> I get when installed with apt-get

this doesn't look bad (as in: there's no error here).

anyhow: *what* did you install with `apt-get`?

> I have tried that and still get same error

the point is you *must* use the same compiler as was used to build your kernel.
this *might* be `/usr/bin/gcc` (which is really just an alias to "some" compiler), it *might* be `/usr/bin/gcc-8` (which is a specific compiler, but there's no guarantee that this is the one used to build the kernel)?

you might also consider adding information (as per the [template](https://github.com/umlaeute/v4l2loopback/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#step-2-describe-your-environment) which you seem to have ignoed), such as the kernel you are actually using, and which distribution.
