### ISSUE TITLE
Compile for Android

### ISSUE THREAD

**Issue by tayyebi** [umlaeute/v4l2loopback#297]
I'm just trying to compile `v4l2loopback` to use on android. In this case I downloaded @torvalds `linux` and put the `include` folder of `linux` kernel inside cloned `v4l2loopback` repository folder to satisfy includes like `#include <linux/vmalloc.h>`.

Then I installed `NDK-bundle` using `Android Studio`  and made my own `toolchain` using command below:
```
python make_standalone_toolchain.py \                  
--arch arm \   
--api 16 \
--install-dir=toolchain-tayyebi
```

Then I tried to compile the `v4l2loopback.c` using the command below:
```
~/Android/Sdk/ndk-bundle/build/tools/toolchain-tayyebi/bin/armv7a-linux-androideabi16-clang -Iinclude v4l2loopback.c
```

There are errors coming one after another.

I'm sure that I'm wrong; nut I did my best. Can anyone help me with this, so I can run `v4l2loopback` on Android?

I was thinking about creating a custom ROM. But I think I have to pass this stage first.

Thanks.

**Comment by umlaeute** [comment]
> There are errors coming one after another.

cool.

please make sure that you can compile the kernel itself (without `v4l2loopback`).
if you have trouble with that, please consult some android or linux-kernel forum/tracker/...
note that **this** tracker is not the right place for discussing on how to compile the kernel.

once you have succeeded building a (running) kernel for your device, and you *still* have trouble compiling `v4l2loopback`, feel free to come back and open a new ticket.

good luck
