### ISSUE TITLE
Load v4l2loopback automatically on boot

### ISSUE THREAD

**Issue by gerben-b** [umlaeute/v4l2loopback#298]
* `v4l2loopback` version: 0.12.5
  * kernel version: 5.4.0-26-generic #30-Ubuntu
  * Distribution (+version):
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal

#### Steps to reproduce:
The module is loaded with modprobe (sudo) and I can't find a way to automate that. I followed several instructions that i found searching the internet but none of them works. I guess they can't all be wrong so I must overlook something. Perhaps security or file attributes, I don know.
If you have any suggestions, that would be appreciated. 

Thanks,
Gerben

**Comment by umlaeute** [comment]
it's done the same as loading any other kernel-module (that is not inserted by hardware-detection).

see [modules-load.d(5)](http://man7.org/linux/man-pages/man5/modules-load.d.5.html) or whatever fits your distribution.

please understand, that this is a general question about operating your linux system and i think that this cannot be covered by v4l2loopback documentation or issue tracker. consult the manual of your distribution instead.
