### ISSUE TITLE
Error Whilst running make

### ISSUE THREAD

**Issue by explodersname** [umlaeute/v4l2loopback#300]
~~~
Building v4l2-loopback driver...
make -C /lib/modules/`uname -r`/build M=/home/explodersname/v4l2loopback modules
make[1]: *** /lib/modules/4.19.98-08076-g24ab33fb8e14/build: No such file or directory.  Stop.
Makefile:42: recipe for target 'v4l2loopback.ko' failed
make: *** [v4l2loopback.ko] Error 2
~~~

is the error that is outputed my my terminal when running the command "make" I have already looked through my files and confirmed that /lib/modules/blahblah/build is a file and am confused as to why it hasnt found it. Maybe I need to find a way to add /root/ to the beginning of the file search? (This often happens when I want to install packages so i must add /root/ to the beginning of the file location if im not already in the directory)

**Comment by umlaeute** [comment]
please install the proper kernel-headers for your system, and make sure that the you can actually build something.
and btw, `/lib/modules/4.19.98-08076-g24ab33fb8e14/build` should not be a *file* (in the narrow sense), but a symlink to the *directory* containing your kernel-headers.

&lt;rant&gt;
it's hard to tell you how tired i am of getting bug-reports like this.
- please read the documentation before submitting bug-reports
- please check the issue tracker before submitting bugs
- please understand that i cannot take care of any quirks you might have done to break your build-system
&lt;/rant&gt;
