### ISSUE TITLE
v4l2loopback-ctl set-caps hangs up at gst-launch-1.0 

### ISSUE THREAD

**Issue by arturcz** [umlaeute/v4l2loopback#307]
* `v4l2loopback` version: 0.12.5
 * kernel version: Linux tardis 4.17.0-1-amd64 #1 SMP Debian 4.17.8-1 (2018-07-20) x86_64 GNU/Linux
 * Distribution (+version): Debian unstable, freshly updated
 * gstreamer1.0-tools 1.16.2-2

When I try to set capabilities using v4l2loopback-ctl command it hangs up when gst-launch-1.0 is called:

~~~
root@tardis:~# v4l2loopback-ctl set-caps "video/x-raw,format=UYVY,width=1920,height=1080" /dev/video0
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Got EOS from element "pipeline0".
Execution ended after 0:00:00.033513059
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
~~~

and it hangs up here.

**Comment by umlaeute** [comment]
i can confirm this (though i have no idea whether the actual problem is with `v4l2loopback` or with `gstreamer`)
