### ISSUE TITLE
Streaming a video to webcam

### ISSUE THREAD

**Issue by JafarBadour** [umlaeute/v4l2loopback#309]
I am trying to stream a video to the webcam but the following error happens

```
[video4linux2,v4l2 @ 0x5583061975c0] ioctl(VIDIOC_G_FMT): Invalid argument
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:0 -- 
Conversion failed!

```
now if i run the command

```
ls /dev/video*
video0 video1
```

modprobe v4l2loopback devices=3

now we have 5 devices after running the aforementioned command:
```
ls /dev/video*
video0 video1 video2 video3 video4
```

Now i want to stream a video file to /dev/video2 
it works perfectly

![image](https://user-images.githubusercontent.com/16943355/82308796-f456e380-99ca-11ea-8750-3868db957629.png)

If i run skype it runs well and skype lets me choose my webcam or the fakewebcam

Cheese for example doesnt work and doesnt let me choose. several different programs do not recognize the fake webcam even after deleting /dev/video0

i also tried to delete video0 and make anotherfile video0 as a symbolic link to /dev/video2

Anyway here is the error when i run 

```
ffmpeg  -re -i  somevideo.webm  -map 0:v -f v4l2 /dev/video0
```

```
[video4linux2,v4l2 @ 0x55c7b054a5c0] ioctl(VIDIOC_G_FMT): Invalid argument
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:0 -- 
Conversion failed!

```

**Comment by umlaeute** [comment]
- you can't "stream a video to a webcam"; webcams are capture-only devices
- deleting a device-file might not be the best idea in general
- when reporting an issue, please *read* the template and follow the instructions you find in there
- esp. you are missing a lot of crucial information, starting with (but not limited to) the v4l2loopback-version
- **and** esp. the part that asks you to look for other issues that report the same problem.

then you are conflating different issues (outputting vs capturing): at the beginning, you state that outputting with ffmpeg "works perfectly", then you have some undefined problems with capturing the stream in cheese and finish with ffmpeg failing to output. that just doesn't make sense.

i understand that you are somehow desperate to get this to work, and started to try all possible things. but this makes it actually harder to help you.

so please:
- read the README
- get the latest and greatest `v4l2loopback`
- follow the README
- if it still doesn't work, check if somebody else had the same problem
- if this is a brand new problem, file a bug report, following the instructions in the template
