### ISSUE TITLE
modprobe: ERROR: could not insert 'v4l2loopback': Exec format error

### ISSUE THREAD

**Issue by willymacoy** [umlaeute/v4l2loopback#313]
I am running MXLinux 

uname -r
Linux mike1907 4.19.0-1-amd64 #1 SMP Debian 4.19.5-2~mx17+1 (2018-12-12) x86_64 GNU/Linux

and not having much luck with a search on this error.

I am not experienced with building from source. If I get an error, I google it and follow the instructions without really understanding what is going on.

This time this strategy didn't work. Can anyone point me in a promising direction?

Thanks

**Comment by umlaeute** [comment]
> and not having much luck with a search on this error.

i don't know how you search, but enterin `Exec format error` in the search-field of [**this** very issue tracker](https://github.com/umlaeute/v4l2loopback/issues?q=Exec+format+error) gives me 4 hits (without *this* one): #147, #238, #260 and #208 

even if we restarted the discussion, i don't think anything new would come out of it.
thus closing.
