### ISSUE TITLE
v4l2loopback could not be inserted

### ISSUE THREAD

**Issue by pranav-vm** [umlaeute/v4l2loopback#320]
I cloned the repo, and proceeded as per the instructions. During make and make install process didn't get any error.

when I hit the command "sudo modprobe v4l2loopback", I got this message on my terminal.

modprobe: ERROR: could not insert 'v4l2loopback': Operation not permitted

I tried all the methods available,but still couldn't solve it. Kindly help!

Thansk :)

**Comment by umlaeute** [comment]
googling for "modprobe: ERROR could not insert Operation not permitted" (that's your error message without the module name), that is the first result it get:

https://unix.stackexchange.com/a/543580/47009
