### ISSUE TITLE
No such file or directory when running 'make'

### ISSUE THREAD

**Issue by JHGelpi** [umlaeute/v4l2loopback#355]
I'm trying to set up a virtual webcam with OBS (obsproject.com) and I'm running into some seemingly strange kernel version "happenings".  When I go to `/usr/src/kernels/` and run `ls -l` I get
```[wgelpi@wgelpi kernels]$ ls -l /usr/src/kernels/
total 4
drwxr-xr-x. 23 root root 4096 Oct  9 04:07 4.18.0-80.11.2.el8_0.x86_64
```
note the _0

When I run `ls -l /usr/src/kernels/$(uname -r)` I'm greeted with the lovely error`ls: cannot access '/usr/src/kernels/4.18.0-144.el8.x86_64': No such file or directory`
....wha???

and thus when I try to run make after cloning the repo I get the following:
```
[wgelpi@wgelpi v4l2loopback]$ make
Building v4l2-loopback driver...
make -C /lib/modules/`uname -r`/build M=/home/wgelpi/github-repos/v4l2loopback modules
make[1]: *** /lib/modules/4.18.0-144.el8.x86_64/build: No such file or directory.  Stop.
make: *** [Makefile:43: v4l2loopback.ko] Error 2
[1] https://github.com/umlaeute/v4l2loopback
```
From what I can tell the only difference in the kernel folder is the `_0`.

**Comment by umlaeute** [comment]
fwiw, this is mentioned in the [README](https://github.com/umlaeute/v4l2loopback#dependencies).

it mentions `3.18.0-trunk-rpi` vs `3.18.7-v7+`, but really this is just an example and applies to `4.18.0-144.el8.x86_64` vs `4.18.0-80.11.2.el8_0.x86_64`.

the kernel and headers must have **exactly** the same version.
