### ISSUE TITLE
Error : Internal Data Stream Error

### ISSUE THREAD

**Issue by mehdizayene** [umlaeute/v4l2loopback#363]
Hello, I am using a Theta V camera linked via USB and wanted to use lookpback to do a stream.
That's what I get as an error : Error: Internal data stream error.
I really have no idea on how to fix this.. any ideas please ?
Thank you very much

**Comment by umlaeute** [comment]
it seems you somehow missed our detailed ["how to report a bug" instructions](https://github.com/umlaeute/v4l2loopback/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) when submitting this issue.
it's really a mandatory read.

esp. you need to do the following:

- check [this issue tracker](https://github.com/umlaeute/v4l2loopback/issues/) (including closed tickets) for similar issues and see whether there is information to help you. to quote the bug-template:

> Please look through the list of issues (*open* and **closed** ones alike), to see whether you problem has been reported before. Probably you can find a solution to your problem without having to create a new ticket.

- what's the module version?
- what's the kernel version?

please also *remove* your screenshot (a mostly black screen that shows how you call some random script is not helping anybody) with the actual gstreamer pipeline you are trying to run. please paste the pipeline **as text**.
