### ISSUE TITLE
error: implicit declaration of function 'idr_for_each'

### ISSUE THREAD

**Issue by tachang** [umlaeute/v4l2loopback#384]
It looks like some recent changes added idr_for_each and idr_find.
These functions look like they are only available on newer kernels. I am on 3.10.14 so wondering if there is a way to backport? Or would you be open to a PR that backported it.

**Comment by umlaeute** [comment]
3.10.14? sigh. afaik, the linux-3.10 has seen [EOL in 2017](https://www.spinics.net/lists/stable/msg128642.html).

I'm not opposed to such a PR, but it must be easy to rip the legacy support out again (in the light of #268 I'd rather not accumulate more cruft than necessary).
also note that there might be more obstacles when backporting than just the missing IDR support.

see also: https://github.com/umlaeute/v4l2loopback/pull/345#issuecomment-707629763
