### ISSUE TITLE
Support paired capture/output devices

### ISSUE THREAD

**Issue by hamishcampbell** [umlaeute/v4l2loopback#40]
It seems that in some situations, devices that are both capture and output devices will be ignored by applications.

For example, Chrome will not recognize a V4l2loopback device:

https://code.google.com/p/chromium/issues/detail?id=139356

The Chromium guys have been using v4l2loopback for WebRTC testing, and have patched around this:

https://code.google.com/p/chromium/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Iteration%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=&id=142568

Their solution is to pair devices such that:

`modprobe v4l2loopback devices=2`

Provides an output device on `/dev/video1` that streams from a capture device at `/dev/video2`

I would find it useful to have this capability optionally provided by v4l2loopback.

For example:

`modprobe v4l2loopback devices=2 pair` or similar (arg suggestions welcome)

I've forked and intend to add this for my own purposes. If others would like to review & test, would it be worth pushing upstream?

**Comment by madovsky** [comment]
Hi, so what option does it need to allow chrome list v4l2loopback today?
thanks
