### ISSUE TITLE
Support changing FPS without root

### ISSUE THREAD

**Issue by letmaik** [umlaeute/v4l2loopback#411]
Currently, FPS can be changed with root permissions by writing to `/sys/devices/virtual/video4linux/video0/format`. Most other settings don't require root, like setting the frame size, pixel format etc. If technically possible, it would be nice to be able to set FPS without root.

**Comment by umlaeute** [comment]
how about this?

~~~sh
sudo chgrp video /sys/devices/virtual/video4linux/video*/format
sudo chmod g+w   /sys/devices/virtual/video4linux/video*/format
~~~

**Comment by umlaeute** [comment]
to make this persistent, you would use something like `udev`.

and, lo-and-behold! there's an [example udev rule](https://github.com/umlaeute/v4l2loopback/blob/main/udev/60-persistent-v4l2loopback.rules) in the repository that does *exactly* that.

https://github.com/umlaeute/v4l2loopback/blob/f62fb9076b6313e5eb82fdcaceadb6b3052f346e/udev/60-persistent-v4l2loopback.rules#L9-L12

**Comment by letmaik** [comment]
Is there a reason why this isn't the default? Seems if `/dev/videox` is in group `video` maybe the rest should also be?

**Comment by umlaeute** [comment]
afaict, this is technically not possible.
