### ISSUE TITLE
v4l2-ctl -d /dev/video2 --get-fmt-video errors out with  "Invalid argument"

### ISSUE THREAD

**Issue by compenguy** [umlaeute/v4l2loopback#436]
This may be related to issue #247, which others were able to fix by updating to a newer version of v4l2loopback.

### Step 2: Describe your environment

  * `v4l2loopback` version: 0.12.5 (tried with both ubuntu 21.04 `v4l2loopback-dkms` package as well as git HEAD as of 2021-06-10)
  * kernel version: `Linux hercules 5.11.0-18-generic #19-Ubuntu SMP Fri May 7 14:22:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
  * Distribution (+version): `Ubuntu 21.04`
  
#### Steps to reproduce:

  1. Ensure module is loaded (`lsmod | grep v4l2loopback`)
  2. Ensure correct device filename under `/dev` (`cat /sys/devices/virtual/video4linux/video2/name`)
  3. Run `v4l2-ctl -d /dev/video2 --get-fmt-video`
  
#### Observed Results:

  * error output `VIDIOC_G_FMT: failed: Invalid argument` with exit code 255
  
#### Expected Results:

  * List current configuration for video capture
  
#### Interesting Observations

Running the application under `strace` shows the device opening correctly:

```
openat(AT_FDCWD, "/dev/video2", O_RDWR) = 3
```

A number of other ioctls complete correctly:

```
ioctl(3, VIDIOC_QUERYCAP, {driver="v4l2 loopback", card="v4l2loopback", bus_info="platform:v4l2loopback-002", version=KERNEL_VERSION(5, 11, 17), capabilities=V4L2_CAP_VIDEO_M2M|V4L2_CAP_EXT_PIX_FORMAT|V4L2_CAP_READWRITE|V4L2_CAP_STREAMING|V4L2_CAP_DEVICE_CAPS, device_caps=V4L2_CAP_VIDEO_M2M|V4L2_CAP_EXT_PIX_FORMAT|V4L2_CAP_READWRITE|V4L2_CAP_STREAMING}) = 0
ioctl(3, VIDIOC_QUERY_EXT_CTRL, {id=V4L2_CTRL_FLAG_NEXT_CTRL|V4L2_CTRL_FLAG_NEXT_COMPOUND|0 /* V4L2_CID_??? */ => V4L2_CTRL_CLASS_USER+0x1, type=V4L2_CTRL_TYPE_CTRL_CLASS, name="User Controls", ...}) = 0
ioctl(3, VIDIOC_TRY_EXT_CTRLS, {ctrl_class=0 /* V4L2_CTRL_CLASS_??? */, count=0}) = 0
ioctl(3, VIDIOC_QUERYCTRL, {id=V4L2_CTRL_FLAG_NEXT_CTRL|0 /* V4L2_CID_??? */ => V4L2_CTRL_CLASS_USER+0x1, type=V4L2_CTRL_TYPE_CTRL_CLASS, name="User Controls", ...}) = 0
ioctl(3, VIDIOC_G_SELECTION, 0x7fff64e51060) = -1 ENOTTY (Inappropriate ioctl for device)
ioctl(3, VIDIOC_QUERYCAP, {driver="v4l2 loopback", card="v4l2loopback", bus_info="platform:v4l2loopback-002", version=KERNEL_VERSION(5, 11, 17), capabilities=V4L2_CAP_VIDEO_M2M|V4L2_CAP_EXT_PIX_FORMAT|V4L2_CAP_READWRITE|V4L2_CAP_STREAMING|V4L2_CAP_DEVICE_CAPS, device_caps=V4L2_CAP_VIDEO_M2M|V4L2_CAP_EXT_PIX_FORMAT|V4L2_CAP_READWRITE|V4L2_CAP_STREAMING}) = 0
newfstatat(3, "", {st_mode=S_IFCHR|0660, st_rdev=makedev(0x51, 0), ...}, AT_EMPTY_PATH) = 0
```

But the ioctl in question fails as described:

```
ioctl(3, VIDIOC_G_FMT, {type=V4L2_BUF_TYPE_VIDEO_CAPTURE}) = -1 EINVAL (Invalid argument)
```

A similar failure occurs in a rust program I'm developing that follows a similar call profile, observed with both VIDIOC_G_FMT and VIDIOC_S_FMT.

The strange part is that running the Linux-Fake-Background-Webcam project's `fake.py`, built on top of `pyfakewebcam`, works just fine:

```
openat(AT_FDCWD, "/dev/video2", O_WRONLY|O_SYNC|O_CLOEXEC) = 4
mmap(NULL, 4149248, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff7cb50a000
mmap(NULL, 6221824, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff7caf1b000               
mmap(NULL, 2076672, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff7cad20000       
ioctl(4, VIDIOC_S_FMT, {type=V4L2_BUF_TYPE_VIDEO_OUTPUT, fmt.pix={width=1920, height=1080, pixelformat=v4l2_fourcc('Y', 'U', 'Y', 'V') /* V4L2_PIX_FMT_YUYV */, field=V4L2_FIELD_NONE, bytesperline=3840, sizeimage=4147200, colorspace=V4L2_CO
LORSPACE_JPEG}} => {fmt.pix={width=1920, height=1080, pixelformat=v4l2_fourcc('Y', 'U', 'Y', 'V') /* V4L2_PIX_FMT_YUYV */, field=V4L2_FIELD_NONE, bytesperline=3840, sizeimage=4149248, colorspace=V4L2_COLORSPACE_SRGB}}) = 0
```

To be clear, I first encountered this issue while developing a rust port of pyfakewebcam, and the issue I initially ran into was related to this error being returned by `VIDIOC_S_FMT`, but in trying to debug that issue I discovered that it also occurs for `VIDIOC_G_FMT`, and reproduces using the distribution-packaged version of `v4l2-ctl`, which seems like a fair minimal reproducing case.

**Comment by umlaeute** [comment]
> #### Expected Results:
> 
>     * List current configuration for video capture

this is what you actually get.
with `--get-fmt-video`  you *query the video capture format*. Since there is no producer attached to the loopback device, you cannot really capture from the device yet.
you could use `--get-fmt-video-out` the query the output format.
or attach a producer, and *then* run  `--get-fmt-video` which will give you the current configuration for the video capture.
