### ISSUE TITLE
[Makefile:46: v4l2loopback.ko] Error 2

### ISSUE THREAD

**Issue by rejucer** [umlaeute/v4l2loopback#458]
~~~
### pi@raspberrypi:/v4l2loopback $ make
Building v4l2-loopback driver...
make -C /lib/modules/`uname -r`/build M=/v4l2loopback modules
make[1]: *** /lib/modules/5.10.17-v7l+/build : Aucun fichier ou dossier de ce type. Arrêt.
make: *** [Makefile:46: v4l2loopback.ko] Error 2
~~~

I have a problem at "make" it looks like i dont have the goods Kernel headers as I read on differents sites but i don't know how to fix this ^^
Can you help me please ?

**Comment by umlaeute** [comment]
>  Can you help me please ?

yes. please read the [README](https://github.com/umlaeute/v4l2loopback#dependencies), it has a special section on the topic.

> it looks like i dont have the goods Kernel headers 

seems so.
i  really cannot give more help (there are hundreds of different kernels and (linux distros) out there, and the only requirement to build `v4l2loopback` is that the headers match your kernel. please consult the documentation of your distribution on how to get the proper headers)
