### ISSUE TITLE
Sites flagging as a virtual device. 

### ISSUE THREAD

**Issue by Buddha-Head** [umlaeute/v4l2loopback#460]
How would we go about editing the name/ID of the virtual device to report as something other than 'OBS Virtual Camera'?

**Comment by umlaeute** [comment]
?

this driver does not name the device "OBS Virtual Camera".
the name is freely choosable by whoever loads the module.

so what happens is that when you use OBS and click on "create virtual device" (or similar), then OBS loads the module and tells it to use the name "OBS Virtual Camera".
so you could either file a feature request with OBS to allow you to pick a different name.
or just create the module yourself with whatever name you want.

as always: please make sure to at least read the README before opening a ticket:
https://github.com/umlaeute/v4l2loopback#options
