### ISSUE TITLE
Please add to Examples page

### ISSUE THREAD

**Issue by ewheelerinc** [umlaeute/v4l2loopback#461]
Please update this page: https://github.com/umlaeute/v4l2loopback/wiki#examples

So it includes this example:

https://github.com/umlaeute/v4l2loopback/wiki/Stream-a-still-JPEG-image

I tried, but it doesn't look like I have access to modify the top wiki page :)

-Eric

**Comment by umlaeute** [comment]
weird (as you were obviously able to create new pages).

anyhow: done
