### ISSUE TITLE
`VIDIOC_ENUM_FRAMEINTERVALS` returns success and invalid data when device isn't ready

### ISSUE THREAD

**Issue by SludgePhD** [umlaeute/v4l2loopback#465]
v4l2loopback devices return success (0) when enumerating frame intervals while no application is writing to them, but they don't actually fill in the returned data. This can confuse userspace since the `type` field of the returned `v4l2_frmivalenum` is 0 (or potentially other invalid values).

https://github.com/umlaeute/v4l2loopback/blob/2e98f45328c0c60198d8b5bdef5f7cfe8964c818/v4l2loopback.c#L850-L859

It seems like this should either return a proper error from the syscall, or it should return a continuous frame interval spanning a very large range (AFAICT it is up to the user to choose how many frames to output in that case).

**Comment by umlaeute** [comment]
afaict this has been fixed with 55113658d03c209b9b591773fb1972f011f5911e
