### ISSUE TITLE
v4l2_buffer sequence number not being set for mmap

### ISSUE THREAD

**Issue by mariannasb** [umlaeute/v4l2loopback#466]
When I'm using gstreamer for streaming frames into the loopback the sequence number on the buffers read out of the loopback stays at zero.
If I use FFMPEG instead to populate the loopback device I see the sequence number increasing as expected.

I have boiled it down to the difference that FFMPEG uses `write()` while gstreamer uses `mmap` (`qbuf`/`dqbuf`).

And by looking at the source code of `v4l2loopback` I can see that `b->sequence` is set to `dev->write_position` in `v4l2_loopback_write()`, but not in `vidioc_qbuf()`.

https://github.com/umlaeute/v4l2loopback/blob/main/v4l2loopback.c#L2122

**Comment by umlaeute** [comment]
merged
