### ISSUE TITLE
Usage Question for splitting capture device

### ISSUE THREAD

**Issue by pauldd** [umlaeute/v4l2loopback#47]
Hello,
Please Sorry this is no real issue but I would like to ask at the source if this would be possible with v4l2loopback.

I have a analog capture device (/dev/video0, PAL) and I want to have a liveview and an option to record at any time to some looseless codecs (maybe ffv1 or mjpeg). 

Is it possible to redirect /dev/video0 to /dev/video1 to have a liveview with mplayer and have another terminal to record for example with ffmpeg/mencoder on /dev/video2? 

Its would be the same principle as opening a capture device in VLC and press the record button, but I cant use VLC because it lacks of the possibility to control the output format and VLC cant be positioned by the standart "-geometry" value that I would like to use on a window-managerless X-Server. VLC outputs only as it comes in (by using the record button). In my case huge raw videos.

**Comment by sadegh** [comment]
+1 It works! Thank you @pauldd, I had similar issue on mac.

**Comment by umlaeute** [comment]
@sadegh so `v4l2loopback` works on mac?

**Comment by moeadham** [comment]
For the next lost soul, this is a terrific command. May the stream be with you.

Take video0 and pipe it to video1 & video2
```
$ gst-launch-1.0 -v v4l2src device=/dev/video0 \
   ! "video/x-raw,format=YUY2,width=640,height=480,framerate=24/1" \
   ! tee name=rec \
   ! queue \
   ! v4l2sink device=/dev/video1 sync=0 \
   rec. \
   ! queue \
   ! v4l2sink device=/dev/video2 sync=0 &
```

**Comment by Moneymel6** [comment]
> Hello,
> Please Sorry this is no real issue but I would like to ask at the source if this would be possible with v4l2loopback.
> 
> I have a analog capture device (/dev/video0, PAL) and I want to have a liveview and an option to record at any time to some looseless codecs (maybe ffv1 or mjpeg).
> 
> Is it possible to redirect /dev/video0 to /dev/video1 to have a liveview with mplayer and have another terminal to record for example with ffmpeg/mencoder on /dev/video2?
> 
> Its would be the same principle as opening a capture device in VLC and press the record button, but I cant use VLC because it lacks of the possibility to control the output format and VLC cant be positioned by the standart "-geometry" value that I would like to use on a window-managerless X-Server. VLC outputs only as it comes in (by using the record button). In my case huge raw videos.

**Comment by Moneymel6** [comment]
https://github.com/umlaeute/v4l2loopback/issues/47#issue-19878925
