### ISSUE TITLE
Dynamic device management triggers Usage text and quits

### ISSUE THREAD

**Issue by porkyoot** [umlaeute/v4l2loopback#474]
### Step 2: Describe your environment

  * `v4l2loopback` version: 0.12.3

          sudo dmesg  | grep -i v4l2loopback

  * kernel version: 5.13.0-40-generic #45~20.04.1-Ubuntu

          uname -a

  * Distribution (+version): elementary OS 6.1 Jólnir

          lsb_release -a

#### Steps to reproduce:

  1. Load the module
  2. v4l2loopback-ctl add -n "loopy doopy" /dev/video7

#### Observed Results:

  * What happened?  This could be a description, log output, etc.
```
Usage:
    /usr/bin/v4l2loopback-ctl [command] [args]

Commands:
     set-fps <FPS> /dev/videoX  Set device fps (if format is already
                                negotiated).

     set-timeout-image <IMAGE> /dev/videoX  Set timeout on device, and 
                                            optionally the placeholder picture,
                                            instead of default null frame.

     set-caps <CAPS> /dev/videoX  Fix format for the device (using GStreamer
                                  caps), so it will be maintained until reset,
                                  regardless of future readers/writers.

Options:
    FPS      frames per second, either as integer ('30') or fraction ('50/2')
    IMAGE    image file ("no-input.png"), or 'videotestsrc'
    CAPS     GStreamer caps ("video/x-raw, format=UYVY, width=640, height=480"),
             or 'any'
    /dev/videoX  the v4l2-loopback device file you want to act on
```

#### Expected Results:

  * What did you expect to happen?
  * Create a v4l2loopback device without output.

#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by umlaeute** [comment]
Your version of `v4l2loopback` (and associated utils) does not have dynamic device management.
