### ISSUE TITLE
Wrong v4l2loopback loaded version and missing /dev/v4l2loopback

### ISSUE THREAD

**Issue by jvmf1** [umlaeute/v4l2loopback#517]
* kernel version: 5.15.0-56-generic

  * Distribution (+version): Ubuntu 22.04.1 LTS

Installation steps I've did:

```sh
sudo apt remove v4l2loopback-dkms v4l2loopback-utils
sudo make all && sudo make install-all
sudo depmod -a
./currentversion.sh # 0.12.7
sudo modprobe -r v4l2loopback
sudo modprobe v4l2loopback
v4l2loopback-ctl query 0 # unable to open control device '/dev/v4l2loopback': No such file or directory
sudo dmesg | tail -1 # [ 1994.547670] v4l2loopback driver version 0.12.5 loaded
```
I've expected the last command to return version 0.12.7. and the `v4l2loopback-ctl` to work. But my guess is that it didn't work because of the different version.

Am I missing something?

**Comment by umlaeute** [comment]
you might want to check the output of:

```sh
/sbin/modinfo v4l2loopback
```
