### ISSUE TITLE
I can't create a virtual webcam

### ISSUE THREAD

**Issue by Bitchlinux** [umlaeute/v4l2loopback#524]
I can't create a virtual webcam, I give the exclusive command with the number and when I give the command to see which existing webcams, the one I created just doesn't appear there, what's going on???

**Comment by umlaeute** [comment]
- which version of `v4l2loopback`
- which kernel
- which distribution
- how did you "create a virtual webcam"
- what do you mean with "the exclusive command"
- what do you mean with " the command to see which existing webcams"
- why didn't you use follow the bug-template?

feel free to provide more information, and I might re-open this issue.
