### ISSUE TITLE
v4l2loopback as built-in module is not working

### ISSUE THREAD

**Issue by LinuxFanatic777** [umlaeute/v4l2loopback#53]
I'm using custom kernel which is compiled from source code (kernel.org).
When I compile v4l2loopback as separate .ko module then "insmod
v4l2loopback.ko devices=8" working fine. But when I using it as
built-in driver inside Linux kernel it's not going to work:

drivers/media/v4l2-core/Kconfig
     +config V4L2_LOOPBACK
     +    tristate "V4L2 loopback device"
     +    ---help---
     +      V4L2 loopback device

drivers/media/v4l2-core/Makefile
     +obj-$(CONFIG_V4L2_LOOPBACK) += v4l2loopback.o

.config
     +CONFIG_V4L2_LOOPBACK=m

It can be built as ko-module and this scenario OK, but when built-in -
module successfully builds, however after system startup I can't see
any /dev/video devices. Of course, before any try, I did the following
modifications in drivers/media/v4l2-core/v4l2loopback.c:

     #define MAX_DEVICES 8
     static int devices = 8;
     module_param(devices, int, 8);
     MODULE_PARM_DESC(devices, "how many devices should be created");
     //static int video_nr[MAX_DEVICES] = { [0 ... (MAX_DEVICES - 1)] = -1 };
     static int video_nr[MAX_DEVICES] = { 0, 1, 2, 3, 4, 5, 6, 7 };

I expect to see `/dev/video0...7` after boot, but unfortunately I can't
see any device nodes...

Is there any way to make it working as built-in driver? Can't see in dmesg anything about v4l2loopback.

P.S.
       LD      arch/x86/vdso/built-in.o
       LD      arch/x86/built-in.o
       CC      drivers/media/v4l2-core/v4l2loopback.o <<< OK
       LD      drivers/media/v4l2-core/built-in.o
       LD      drivers/media/built-in.o
       LD      drivers/built-in.o
       LINK    vmlinux

Also, running kernel with built-in module in file /proc/kallsyms contains v4l2_loopback_close, v4l2_loopback_mmap and other functions, and strange that v4l2_loopback_fops/ioctl_ops exists in System.map, but not in running kernel.

**Comment by dukelec** [comment]
For build in, add one line to the end:

late_initcall(init_module);

**Comment by LinuxFanatic777** [comment]
Wow! Two years... I didn't tested this patch yet, but thank you anyway ^_^

2015-11-12 14:51 GMT+02:00 dukelec <notifications@github.com>:
