### ISSUE TITLE
Ubuntu with kernel 6.3.7 don't load module

### ISSUE THREAD

**Issue by Lorenzo-SF** [umlaeute/v4l2loopback#546]
Hi everyone!

Yesterday i installed a new kernel version in my ubuntu (6.3.7) from 5.19.0.45.46. With "old" kernel i use iriun webcam for use an old smartphone like a webcam, but since i upgraded to the new kernel it doesn't work. Now, when i start the application, show this message:

```
Initialization failed
You may want to run:
sudo rmmod v4l2loopback; sudo modprobe v4l2loopback
```
If i try to run, shows this messages:
```
rmmod: ERROR: Module v4l2loopback is not currently loaded
modprobe: ERROR: could not insert 'v4l2loopback': Key was rejected by service
```
Someones knows something about it?
Thanks!

**Comment by umlaeute** [comment]
this is a problem with secure boot and (not) signed modules:
https://github.com/umlaeute/v4l2loopback#troubleshooting
