### ISSUE TITLE
Why only 8 devices max?

### ISSUE THREAD

**Issue by iwuvjhdva** [umlaeute/v4l2loopback#55]
Hey, found this line while observing the code:
# define MAX_DEVICES 8

We actually need at least 100 devices for our project - is there any workaround for that besides forking?

Thank you!

**Comment by cetinakat** [comment]
Hello, I used to v4l2loopback for android emulators and it works with great till 100 cameras but when I run "emulator -webcam-list" it just show 8 cameras. Are there any ideas why is that?

Emulator webcam list: http://prntscr.com/j7sgsm
device list: http://prntscr.com/j7shzd

**Comment by umlaeute** [comment]
@cetinakat  so you have 100 working v4l2loopback devices, and some application only shows only a subset and you suspect that the problem is with the 100 devices? have you checked whether your emulator allows more than 8 cameras?

**Comment by karllacr** [comment]
Hi,
I am facing this problem and I did use all the recommendations, but i didn't have success.
By "all the recommendations" I mean: change the code and recompile, and add **make KCPPFLAGS="-DMAX_DEVICES=100"** during the build-process


-----------------------------------------------------------
# dmesg  | grep -i v4l2loopback
[    5.984450] v4l2loopback: loading out-of-tree module taints kernel.
[    5.984467] v4l2loopback: module verification failed: signature and/or required key missing - tainting kernel
[    5.984638] v4l2loopback driver version 0.9.1 loaded
[  652.694912] v4l2loopback: number of devices is limited to: 8
[  652.695210] v4l2loopback driver version 0.9.1 loaded
------------------------------------------------------------

# uname -a
 4.15.0-47-generic #50~16.04.1-Ubuntu SMP Fri Mar 15 16:06:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
------------------------------------------------------------

# lsb_release -a
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
---------------------------------------------------------
When I run:

modprobe v4l2loopback devices=100

It just create 8 devices... If anyone can help, I would be very grateful :)

**Comment by umlaeute** [comment]
@karllacr most likely you have conflicting installations of the module and your kernel picks the wrong one.
- did you "install" the newly compiled module
- did you uninstall any leftovers of old compilations of the module

also note that running `make` after compilation (e.g. with other build targets like `make install` or `make modprobe`), might recompile the module if you don't add the `KCPPFLAGS="-DMAX_DEVICES=100"` (or whatever flags you added) to the build process *again*.
to be save, pass the flags to all invocations of `make`.

**Comment by karllacr** [comment]
@umlaeute  I did as you recommended and it worked!
Thank you :D
