### ISSUE TITLE
Does v4l2loopback support V4L2_BUF_TYPE_VIDEO_OUTPUT_MPLANE?

### ISSUE THREAD

**Issue by sanbrother** [umlaeute/v4l2loopback#552]
Hi, thank you for your awesome work.

I didn't find out how to use V4L2_BUF_TYPE_VIDEO_OUTPUT_MPLANE. Could you give me some guide how to use this?
I want to create a v4l2loopback device that supports multi plane capture.

**Comment by umlaeute** [comment]
i'm not trying to shut you down, but to quote the issue template:

## Ask a Question
For general questions (and answers) about the usage of this module, please check the `v4l2loopback` tag on [Unix & Linux @ StackExchange](https://unix.stackexchange.com/questions/tagged/v4l2loopback)
## Ask a Dev-Question
There's also a `v4l2loopback` tag on [StackOverflow](https://stackoverflow.com/questions/tagged/v4l2loopback) (which has a larger userbase than the "Unix & Linux" group, although strictly speaking "usage"-questions are off-topic there)
