### ISSUE TITLE
resolution 2048x1 does not work

### ISSUE THREAD

**Issue by Katze719** [umlaeute/v4l2loopback#573]
i can not set the resolution to `2048x1` i guess this is due to hardcoded macros:

```c++
#define V4L2LOOPBACK_SIZE_MIN_WIDTH 48
#define V4L2LOOPBACK_SIZE_MIN_HEIGHT 32
```

what is the reason behind not letting the user pick resolutions smaller than 48x32?

**Comment by umlaeute** [comment]
the reason is a simple sanity check :-)

if changing the minimum width/height to `1` works for you (or better `MIN_WIDTH=2, MIN_HEIGHT=1`), we could change that.

**Comment by Katze719** [comment]
I'd love to, that would be perfect

**Comment by umlaeute** [comment]
what i meant is: can you confirm that it is actually working for you if you make these changes?

**Comment by Katze719** [comment]
if i compile it myself it works with ffmpeg as producer

**Comment by Katze719** [comment]
just confirmed, works on arm64 and x86_64
