### ISSUE TITLE
getNextFrame no data errno:0 Success

### ISSUE THREAD

**Issue by javiluco24** [umlaeute/v4l2loopback#580]
Hi team!

I´m trying to view my video capture camera over rtsp server, and when execute a server, after random minutes allways get this error and the image freeze.

[NOTICE] /v4l2rtspserver/src/V4L2DeviceSource.cpp:214
	V4L2DeviceSource::getNextFrame no data errno:0 Success

Could you help me? any ideas?

Thanks in advance
BR

**Comment by umlaeute** [comment]
i'm afraid it is impossible to help you with the information you provided.
(when creating a new issue, you get some information about the minimum required information)
