### ISSUE TITLE
chrome cannot detect the dummy video device

### ISSUE THREAD

**Issue by xiaobo-lab** [umlaeute/v4l2loopback#591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Detail

```markdown
i have installed the v4l2loopback through command:

apt-get install v4l2loopback-dkms
```
then，created dummy video device：
```
modprobe v4l2loopback
```
then, use ffmpeg as producer to show a static image:
```
ffmpeg -loop 1 -re -i foo.jpg -f v4l2 -vcodec rawvideo -pix_fmt yuv420p /dev/video2
```
its work just fine with ffplay:
```
ffplay /dev/video2
```
but the problem is chrome cannot detect the device /dev/video2
```


### v4l2loopback version

0.13.2

### kernel version

6.8.0-41-generic

### OS Version

Ubuntu 24.04

### Which CPU are you using?

amd64/x86_64 ("64bit Intel")

**Comment by umlaeute** [comment]
to me, this looks like a problem of `chrome`, rather than `v4l2loopback`
