### ISSUE TITLE
Regarding the Flathub version of OBS Studio loading the v4l2loopback module

### ISSUE THREAD

**Issue by Hao0920** [umlaeute/v4l2loopback#593]
Hello, I am a Steam Deck OLED user who has installed the Flathub version of OBS Studio version 30.2.3. I have also installed the Droidcam plugin to use my phone as a webcam for the Steam Deck, and it is running perfectly. However, I am encountering issues with the virtual camera output. The Wiki suggests that simply loading the v4l2loopback module should suffice; but I am concerned about potential updates that might affect the system's normal operation, and I have not disabled steamos-readonly. So, is it possible to release a Flathub version of the v4l2loopback as a plugin?

**Comment by umlaeute** [comment]
No.

`v4l2loopback` is a kernel module, which is fundamentally not supportable by a thin containerisation framework like `flatpak`.

(If you know of some special tricks to support kernel modules, by all means do share them)
