### ISSUE TITLE
changes for kernel 3.16 replace strict_strto* call with kstrto*

### ISSUE THREAD

**Issue by moosbaue** [umlaeute/v4l2loopback#85]
Hello

line `v4l2loopback.c:506` reads

     if (strict_strtoul(buf, 0, &curr))

From kernel 3.16 onward, this must be replaced by

     if (kstrtoul(buf, 0, &curr))

**Comment by umlaeute** [comment]
thanks.

afaict, this should read kernel *3.18*

it has been fixed a few months ago with 21195cd6.

**Comment by moosbaue** [comment]
sorry, did not read carefully enough

**Comment by umlaeute** [comment]
np. in any case thanks for the suggested fix (even though it was not needed this time...)

**Comment by moosbaue** [comment]
and the version numbering confused me; had 0.8.0 and is still 0.8.0
Imho maybe as a suggestion even though bug fixing, increasing versions are helpfull to some people

**Comment by umlaeute** [comment]
versions are increased for each release.
without release, versions are not increased.
