### ISSUE TITLE
Can't read private key

### ISSUE THREAD

**Issue by hashmuke** [umlaeute/v4l2loopback#88]
I am running ubntu 12.04 and the installation failed with the following output 

hash@hash:~/bin/v4l2loopback[master]$ make
Building v4l2-loopback driver...
make -C /lib/modules/`uname -r`/build M=/home/hash/bin/v4l2loopback modules
make[1]: Entering directory `/usr/src/linux-headers-3.11.0-26-generic'
  CC [M]  /home/hash/bin/v4l2loopback/v4l2loopback.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/hash/bin/v4l2loopback/v4l2loopback.mod.o
  LD [M]  /home/hash/bin/v4l2loopback/v4l2loopback.ko
make[1]: Leaving directory `/usr/src/linux-headers-3.11.0-26-generic'

hash@hash:~/bin/v4l2loopback[master]$ sudo make install 
make -C /lib/modules/`uname -r`/build M=/home/hash/bin/v4l2loopback modules_install
make[1]: Entering directory `/usr/src/linux-headers-3.11.0-26-generic'
  INSTALL /home/hash/bin/v4l2loopback/v4l2loopback.ko
Can't read private key
  DEPMOD  3.11.0-26-generic
make[1]: Leaving directory `/usr/src/linux-headers-3.11.0-26-generic'
depmod -a  `uname -r`

**Comment by umlaeute** [comment]
quoting the answer from a similar (and apart from the error-message totally unrelated) [issue](/slavrn/gm12u320/issues/7)

> "Can't read private key" is not an issue. This just means that you are not Ubuntu maintaner and you don't have access to the private keys, of course. This cannot affect driver functionality.
> According to the log, installation is OK.
