### ISSUE TITLE
Please tag a new release

### ISSUE THREAD

**Issue by kripton** [umlaeute/v4l2loopback#89]
Hello,

I'm using Gentoo Linux and the v4l2loopback-0.8.0 (latest release) does not compile against linux-3.18 or newer (see https://bugs.gentoo.org/show_bug.cgi?id=532894). Would it be possible to tag a new release so that new version can be used with newer kernels? Thank you!

**Comment by kripton** [comment]
Thanks for the tag! Was it intentional or forgotten that the module version hasn't been updated? https://github.com/umlaeute/v4l2loopback/blob/master/v4l2loopback.c#L39

**Comment by umlaeute** [comment]
totally.
nice catch.
thanks
