### ISSUE TITLE
Loopback device not detected by Chromium

### ISSUE THREAD

**Issue by slycheese** [umlaeute/v4l2loopback#91]
I'm trying to use v4l2loopback with WebRTC on an ARM-based Ubuntu system but the v4l2loopback dummy device is not detected by Hangouts, Talky.io, or any of the other WebRTC-based web apps that I've tried. I've tried using Firefox and Chromium, but neither see the loopback source.  The loopback source is detected and shown properly by programs like guvcview, VLC, etc.

**Comment by umlaeute** [comment]
which version of v4l2loopback are you using?

**Comment by umlaeute** [comment]
and please check the `exclusive_caps` parameter, which was introduced in `0.7.0` in order to (according to the NEWS file):

> report CAPTURE/OUTPUT capabilities exclusively (support for Chromium/WebRTC)
