### ISSUE TITLE
udev by-id symlinks

### ISSUE THREAD

**Issue by basinilya** [umlaeute/v4l2loopback#96]
Please add missing attributes to the virtual device so the standard udev rule can create symlinks in /dev/v4l/by-id/ .
Need it, because have to store the device path in zoneminder.
Desired something like this:

```
$ ls -l /dev/v4l/by-id/
total 0
lrwxrwxrwx 1 root root 12 Aug 29 23:06 ???-Loopback-video-index0 -> ../../video0
lrwxrwxrwx 1 root root 12 Aug 29 23:06 ???-Loopback-video-index1 -> ../../video1
lrwxrwxrwx 1 root root 12 Aug 29 23:06 usb-Syntek_Semiconductor_USB_2.0_Video_Capture_Controller-video-index0 -> ../../video3
```

.rules file:

```
$ cat /usr/lib/udev/rules.d/60-persistent-v4l.rules
# do not edit this file, it will be overwritten on update

ACTION=="remove", GOTO="persistent_v4l_end"
SUBSYSTEM!="video4linux", GOTO="persistent_v4l_end"
ENV{MAJOR}=="", GOTO="persistent_v4l_end"

IMPORT{program}="v4l_id $devnode"

SUBSYSTEMS=="usb", IMPORT{builtin}="usb_id"
KERNEL=="video*", ENV{ID_SERIAL}=="?*", SYMLINK+="v4l/by-id/$env{ID_BUS}-$env{ID_SERIAL}-video-index$attr{index}"

# check for valid "index" number
TEST!="index", GOTO="persistent_v4l_end"
ATTR{index}!="?*", GOTO="persistent_v4l_end"

IMPORT{builtin}="path_id"
ENV{ID_PATH}=="?*", KERNEL=="video*|vbi*", SYMLINK+="v4l/by-path/$env{ID_PATH}-video-index$attr{index}"
ENV{ID_PATH}=="?*", KERNEL=="audio*", SYMLINK+="v4l/by-path/$env{ID_PATH}-audio-index$attr{index}"

LABEL="persistent_v4l_end"
```

**Comment by normanr** [comment]
You'd probably be better off writing your own rules. The rules above use the usb attributes, and v4l2loopback isn't a usb device. You could use $attr{name} to get the card_label and populate the symlink with that.
Something like: `KERNEL=="video*", ATTR{max_openers}=="?*", SYMLINK+="v4l/by-id/v4l2loopback-$attr{name}-video"` should work if you put it into `/etc/udev/rules.d/60-persistent-v4l2loopback.rules` and run `sudo udevadm trigger -v -s video4linux` (or just reboot).
